spring:
  application:
    name: 'product'
server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix


logging:
  level:
    com:
      github:
        app:
          product:
            service: debug